[package]
name = "chimitheque_pubchem"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
chimitheque_types = { path = "../chimitheque_types" }
futures = "0.3.31"
governor = "0.10.1"
log = "0.4.28"
urlencoding = "2.1.3"
reqwest = { version = "0.11", features = ["blocking", "json", "gzip", "deflate"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.145"
image = "0.25.8"
env_logger = "0.11.8"
