[package]
name = "chimitheque_pubchem"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
env_logger = "0.11.8"
futures = "0.3.31"
governor = "0.10.1"
image = "0.25.8"
log = "0.4.28"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.145"
ureq = { version = "3", features = ["json"] }
urlencoding = "2.1.3"

chimitheque_types = { path = "../chimitheque_types" }
